import VueMdijs from 'vue-mdijs';
import {
  mdiGithub,
  mdiMenu,
  mdiPencil,
  mdiDelete,
  mdiEye,
  mdiUndo,
  mdiRedo,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatHeader1,
  mdiFormatStrikethrough,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatListChecks,
  mdiLink,
  mdiImage,
  mdiTable,
  mdiFormatQuoteClose,
  mdiCodeTags,
  mdiCog,
  mdiClose,
  mdiChevronDown,
  mdiDotsHorizontal,
  mdiPlus,
} from '@mdi/js';

VueMdijs.add({
  mdiGithub,
  mdiMenu,
  mdiPencil,
  mdiDelete,
  mdiEye,
  mdiFormatBold,
  mdiUndo,
  mdiRedo,
  mdiFormatItalic,
  mdiFormatHeader1,
  mdiFormatStrikethrough,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatListChecks,
  mdiLink,
  mdiImage,
  mdiTable,
  mdiFormatQuoteClose,
  mdiCodeTags,
  mdiCog,
  mdiClose,
  mdiChevronDown,
  mdiDotsHorizontal,
  mdiPlus,
});

export default VueMdijs;
