import Vue from 'vue';
import VueMdijs from 'vue-mdijs';
import {
  mdiMenu,
  mdiPencil,
  mdiDelete,
  mdiEye,
  mdiUndo,
  mdiRedo,
  mdiFormatBold,
  mdiFormatItalic,
  mdiFormatHeader1,
  mdiFormatStrikethrough,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatListChecks,
  mdiLink,
  mdiImage,
  mdiTable,
  mdiFormatQuoteClose,
  mdiCodeTags,
  mdiCog,
  mdiClose,
  mdiChevronDown,
} from '@mdi/js';

VueMdijs.add({
  mdiMenu,
  mdiPencil,
  mdiDelete,
  mdiEye,
  mdiFormatBold,
  mdiUndo,
  mdiRedo,
  mdiFormatItalic,
  mdiFormatHeader1,
  mdiFormatStrikethrough,
  mdiFormatListBulleted,
  mdiFormatListNumbered,
  mdiFormatListChecks,
  mdiLink,
  mdiImage,
  mdiTable,
  mdiFormatQuoteClose,
  mdiCodeTags,
  mdiCog,
  mdiClose,
  mdiChevronDown,
});

Vue.use(VueMdijs);
